# Generated by Django 4.2.15 on 2024-08-25 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_roll_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
