# Generated by Django 4.2.15 on 2024-08-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_remove_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.IntegerField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
