# Generated by Django 4.2.15 on 2024-08-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_roll_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Phone_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
