# Generated by Django 4.2.15 on 2024-08-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_phone_number_student_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Phone_number',
        ),
        migrations.AddField(
            model_name='student',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
