# Generated by Django 4.2.15 on 2024-08-24 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_class_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='students',
        ),
    ]
