# Generated by Django 4.2.15 on 2024-08-25 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_remove_class_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='teacher',
        ),
    ]
