# Generated by Django 4.2.15 on 2024-08-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='grade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
