# Generated by Django 4.2.15 on 2024-08-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0004_mark_grade_delete_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='grade',
            field=models.CharField(blank=True, editable=False, max_length=2, null=True),
        ),
    ]
