# Generated by Django 4.2.15 on 2024-08-24 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_alter_teacher_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
    ]
