# Generated by Django 4.2.15 on 2024-08-26 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='employee_id',
            field=models.IntegerField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
